/* ===== SHARED STUDY MUSIC PLAYER ===== */

/* Media URL resolver. tracks.js stores paths relative to the Playlist/ root
   (e.g. "Playlist/foo.mp3"); set window.R2_MUSIC_BASE in index.html to point
   at a public R2 bucket and we'll fetch from there instead of locally. Empty
   base = serve from same origin (local dev / cPanel-style static hosting).
   Absolute URLs in tracks.js pass through unchanged so individual tracks can
   override the base if needed. */
window.meceeMediaUrl = function (path) {
  if (!path) return '';
  if (/^(https?:|data:|blob:)/i.test(path)) return path;
  const base = (window.R2_MUSIC_BASE || '').replace(/\/+$/, '');
  return base ? base + '/' + path.replace(/^\/+/, '') : path;
};

(function () {
  const VOL_KEY      = "mecee_player_vol";
  const TRACK_KEY    = "mecee_player_track";
  const PLAY_KEY     = "mecee_player_playing";
  const TIME_KEY     = "mecee_player_time";
  const EXPAND_KEY   = "mecee_player_expanded";
  const PLAYLIST_KEY = "mecee_player_playlist";   // selected playlist id

  /* Loaded from Playlist/tracks.js (auto-generated by update_playlist.py).
     New format: window.PLAYLIST_GROUPS = [{id, name, cover, tracks:[…]}, …]
     Legacy format: window.PLAYLIST_TRACKS = [...]
     Fall back gracefully so a stale tracks.js doesn't break the player. */
  function loadGroups() {
    if (typeof window === 'undefined') return [];
    if (Array.isArray(window.PLAYLIST_GROUPS) && window.PLAYLIST_GROUPS.length) {
      return window.PLAYLIST_GROUPS;
    }
    if (Array.isArray(window.PLAYLIST_TRACKS) && window.PLAYLIST_TRACKS.length) {
      return [{ id: 'default', name: 'Default', cover: '', tracks: window.PLAYLIST_TRACKS }];
    }
    return [];
  }

  let GROUPS = loadGroups();

  function pickGroup(id) {
    if (!GROUPS.length) return null;
    return GROUPS.find(g => g.id === id) || GROUPS[0];
  }

  /* When this page is loaded inside the shell iframe, the *shell* owns the audio.
     We hide the in-page widget and forward nav-link clicks up to the shell so it
     can swap iframe.src without ever unloading the audio element. */
  function inIframe() {
    try { return window.top !== window.self; } catch (e) { return true; }
  }

  function installNavForwarder() {
    document.addEventListener('click', e => {
      const a = e.target.closest('a[href]');
      if (!a) return;
      const href = a.getAttribute('href') || '';
      const m = href.match(/^(tracker|index|routine|chat|library)\.html(?:[?#].*)?$/);
      if (!m) return;
      e.preventDefault();
      let target = m[1];
      if (target === 'index') target = 'tracker';
      try { window.parent.postMessage({ type: 'nav', href: target }, '*'); } catch (_) {}
    });
  }

  function init() {
    const widget = document.getElementById('playerWidget');

    if (inIframe()) {
      // The shell owns the player — hide any in-page widget and forward nav clicks.
      if (widget) widget.style.display = 'none';
      installNavForwarder();
      return;
    }

    if (!widget) return; // page has no widget mount

    const thumb    = document.getElementById('playerThumb');
    const title    = document.getElementById('playerTitle');
    const sub      = document.getElementById('playerSub');
    const playBtn  = document.getElementById('playerPlay');
    const prevBtn  = document.getElementById('playerPrev');
    const nextBtn  = document.getElementById('playerNext');
    const volEl    = document.getElementById('playerVol');
    const progress = document.getElementById('playerProgress');
    const audio    = document.getElementById('playerAudio');

    let currentGroup = pickGroup(localStorage.getItem(PLAYLIST_KEY) || 'default');
    let currentTrack = Math.min(
      parseInt(localStorage.getItem(TRACK_KEY) || "0", 10) || 0,
      (currentGroup ? currentGroup.tracks.length : 1) - 1
    );
    if (currentTrack < 0) currentTrack = 0;

    const savedVol   = parseFloat(localStorage.getItem(VOL_KEY) || "0.6");
    audio.volume = Math.max(0, Math.min(1, savedVol));
    volEl.value = Math.round(audio.volume * 100);

    let lastTimeSave = 0;

    function tracks() { return (currentGroup && currentGroup.tracks) || []; }

    function loadTrack(i, autoplay, restoreTime) {
      const arr = tracks();
      if (!arr.length) {
        title.textContent = 'No tracks';
        sub.textContent = currentGroup ? currentGroup.name : '—';
        return;
      }
      currentTrack = (i + arr.length) % arr.length;
      const t = arr[currentTrack];
      audio.src = encodeURI(window.meceeMediaUrl(t.file));
      title.textContent = t.title;
      sub.textContent = `${currentGroup.name} · ${currentTrack + 1} / ${arr.length}`;
      const cover = t.cover || currentGroup.cover || '';
      const coverUrl = cover ? window.meceeMediaUrl(cover) : '';
      thumb.style.setProperty('--player-thumb-cover',
        coverUrl ? `url("${encodeURI(coverUrl).replace(/"/g, '\\"')}")` : 'none');
      localStorage.setItem(TRACK_KEY, String(currentTrack));
      localStorage.setItem(PLAYLIST_KEY, currentGroup.id);

      if (restoreTime) {
        const onMeta = () => {
          audio.removeEventListener('loadedmetadata', onMeta);
          const saved = parseFloat(localStorage.getItem(TIME_KEY) || "0");
          if (saved > 0 && audio.duration && saved < audio.duration - 1) {
            try { audio.currentTime = saved; } catch (e) {}
          }
          if (autoplay) playAudio();
        };
        audio.addEventListener('loadedmetadata', onMeta);
      } else {
        localStorage.setItem(TIME_KEY, "0");
        if (autoplay) playAudio();
      }
    }

    function playAudio() {
      audio.play().then(() => {
        playBtn.textContent = '⏸';
        widget.classList.add('playing');
        localStorage.setItem(PLAY_KEY, '1');
      }).catch(() => {
        playBtn.textContent = '▶';
      });
    }

    function pauseAudio() {
      audio.pause();
      playBtn.textContent = '▶';
      widget.classList.remove('playing');
      localStorage.setItem(PLAY_KEY, '0');
    }

    function setExpanded(on) {
      widget.classList.toggle('expanded', on);
      localStorage.setItem(EXPAND_KEY, on ? '1' : '0');
    }

    /* Public API for the playlist picker (lives in the shell UI). */
    function switchPlaylist(id) {
      const g = pickGroup(id);
      if (!g || !g.tracks.length) return;
      currentGroup = g;
      currentTrack = 0;
      localStorage.setItem(PLAYLIST_KEY, g.id);
      loadTrack(0, true, false);
    }
    /* Play a specific track inside a specific playlist — used by the picker
       when the user clicks an individual song tile (not just a playlist). */
    function playTrack(playlistId, trackIdx) {
      const g = pickGroup(playlistId);
      if (!g || !g.tracks.length) return;
      currentGroup = g;
      localStorage.setItem(PLAYLIST_KEY, g.id);
      loadTrack(Math.max(0, Math.min(trackIdx | 0, g.tracks.length - 1)), true, false);
    }
    function refreshFromManifest() {
      GROUPS = loadGroups();
      currentGroup = pickGroup(currentGroup ? currentGroup.id : null) || GROUPS[0];
      if (!currentGroup) return;
      if (currentTrack >= currentGroup.tracks.length) currentTrack = 0;
      // Re-render label without changing the audio src if the same track still exists.
      const arr = tracks();
      if (arr[currentTrack]) {
        sub.textContent = `${currentGroup.name} · ${currentTrack + 1} / ${arr.length}`;
      }
      document.dispatchEvent(new CustomEvent('mecee-player-manifest', { detail: { groups: GROUPS } }));
    }
    window.MeceePlayer = {
      switchPlaylist,
      playTrack,
      refreshFromManifest,
      getGroups:  () => GROUPS.slice(),
      getCurrent: () => currentGroup ? { id: currentGroup.id, trackIdx: currentTrack } : null,
    };

    thumb.addEventListener('click', () => {
      setExpanded(!widget.classList.contains('expanded'));
    });

    playBtn.addEventListener('click', () => {
      if (audio.paused) playAudio(); else pauseAudio();
    });
    prevBtn.addEventListener('click', () => loadTrack(currentTrack - 1, true, false));
    nextBtn.addEventListener('click', () => loadTrack(currentTrack + 1, true, false));

    volEl.addEventListener('input', e => {
      const v = parseInt(e.target.value, 10) / 100;
      audio.volume = v;
      localStorage.setItem(VOL_KEY, String(v));
    });

    audio.addEventListener('ended', () => loadTrack(currentTrack + 1, true, false));
    audio.addEventListener('timeupdate', () => {
      if (audio.duration) {
        progress.style.width = ((audio.currentTime / audio.duration) * 100) + '%';
      }
      const now = Date.now();
      if (now - lastTimeSave > 1000) {
        localStorage.setItem(TIME_KEY, String(audio.currentTime));
        lastTimeSave = now;
      }
    });
    audio.addEventListener('error', () => {
      sub.textContent = 'Error loading track';
    });

    /* Save state right before navigating away so the next page picks up
       exactly where we left off. */
    window.addEventListener('pagehide', () => {
      localStorage.setItem(TIME_KEY, String(audio.currentTime || 0));
      localStorage.setItem(PLAY_KEY, audio.paused ? '0' : '1');
    });

    /* Restore expansion state from last page */
    if (localStorage.getItem(EXPAND_KEY) === '1') {
      widget.classList.add('expanded');
    }

    /* Load the current track and try to pick up at the saved position */
    loadTrack(currentTrack, false, true);

    /* If we were playing before, auto-resume on first user interaction
       (browser autoplay policy requires a user gesture) */
    if (localStorage.getItem(PLAY_KEY) === '1') {
      const resume = () => {
        if (audio.paused) {
          const onMeta2 = () => {
            audio.removeEventListener('loadedmetadata', onMeta2);
            const saved = parseFloat(localStorage.getItem(TIME_KEY) || "0");
            if (saved > 0 && audio.duration && saved < audio.duration - 1) {
              try { audio.currentTime = saved; } catch (e) {}
            }
            playAudio();
          };
          if (audio.readyState >= 1) {
            const saved = parseFloat(localStorage.getItem(TIME_KEY) || "0");
            if (saved > 0 && audio.duration && saved < audio.duration - 1) {
              try { audio.currentTime = saved; } catch (e) {}
            }
            playAudio();
          } else {
            audio.addEventListener('loadedmetadata', onMeta2);
          }
        }
      };
      document.addEventListener('click', resume, { once: true });
      document.addEventListener('keydown', resume, { once: true });
      document.addEventListener('touchstart', resume, { once: true });
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
